version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: sparkles-minecraft-server_ui_1
      APP_PORT: 25566

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: sparkles-minecraft-server_minecraft_1
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: VANILLA
      VERSION: LATEST
      MEMORY: 1G
      ENABLE_RCON: "true"
      RCON_PASSWORD: "sparkles_mc_rcon"
    ports:
      - "25565:25565"
    volumes:
      - ${APP_DATA_DIR}/minecraft:/data

  ui:
    image: exxxa/sparkles-minecraft-server-ui:1.1.0
    container_name: sparkles-minecraft-server_ui_1
    restart: unless-stopped
    environment:
      MINECRAFT_CONTAINER: sparkles-minecraft-server_minecraft_1
      DATA_DIR: /minecraft-data
      PORT: 25566
      RCON_PASSWORD: "sparkles_mc_rcon"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/minecraft:/minecraft-data
    depends_on:
      - minecraft
