version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-recipe-website_app_1
      APP_PORT: 2382

  app:
    image: exxxa/recipe-website:latest
    container_name: sparkles-recipe-website_app_1
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "2383:2382"
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
      - "${APP_DATA_DIR}/uploads:/app/uploads"
    environment:
      PORT: "2382"
      DATABASE_URL: "file:/app/data/recipes.db"
      JWT_SECRET: "${APP_SEED}"
      ALLOWED_ORIGIN: "https://recipe.pabloushka.org"
